project:
  type: website
  

website:
  page-navigation: true
  title: "Research Data Services R Workshops at Georgia State University"
  description: "Homepage Research Data Services R Workshops"
  site-url: "https://joshuafayallen.github.io/
research-data-services-r-workshops/"

  repo-url: https://github.com/joshuafayallen/research-data-services-r-workshops
  repo-actions: [edit, issue]

 # opengraph: true
 # twitter-card:
 #   creator: "@minebocek"
 #   image: "https://raw.githubusercontent.com/joshuafayallen/research-data-services-r-workshops/main/images/avatar.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Josh Allen"
    background: "#D9E3E4"

  sidebar:
    background: "#97CAEB"
    logo: "images/avatar.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/joshuafayallen/research-data-services-r-workshops
      - icon: person-fill
        text: "Sakai"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Workshop Information"
        contents:
          - href: course-overview.qmd
            text: Overview
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Installing R
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
      - section: "Workshop Materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Workshop 1- Getting Started in R"
          - href: weeks/week-2.qmd
            text: "Tidyverse and Manipulating Data"
          - href: weeks/week-3.qmd
            text: "Data  Visualization and Mapping"
          - href: weeks/week-4.qmd
            text: "Statistical Modeling in R"


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: source