---
title: "Georgia State Research Data Services R Workshop"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

This is where all the materials that are presented in the RDS R workshops will live. Note that this is maintained by me(Josh Allen) so please direct any questions you have to me at jallen108\[at\]gsu\[dot\]edu

::: column-screen-inset-right


| Date         | Location & Time                           | Title                           | Materials |
|--------------|-------------------------------------------|---------------------------------|-----------|
| September 7  | Online: 11:00 - 1:00 pm                   | Getting Started in R            |[1](/weeks/week-1.html)|
| September 21 | Online: 11:00-1:00 pm                     | Tidyverse and Manipulating Data |[2](/weeks/week-2.qmd)           |
| September 30 | Online: 11:00-1:00 pm                     | Data Visualization and Mapping  | [3](/weeks/week-3.qmd)          |
| October 7    | Online: 11:00-1:00 pm                     | Statistical Modelling  in R         |   [4](/weeks/week-4.qmd)        |
| October 20   | Classroom 2, Library North 2 12:00-2:00pm | Getting Started in R            | [1](/weeks/week-1.qmd)       |
| October 27   | Classroom 2, Library North 2 12:00-2:00pm | Tidyverse and Manipulating Data |  [2](/weeks/week-2.qmd)         |
| November 3   | Classroom 2, Library North 2 12:00-2:00pm | Data Visualization and Mapping  |    [3](/weeks/week-3.qmd)       |
| November 10  | Classroom 2, Library North 2 12:00-2:00pm | Statistical Modelling in R          |     [4](/weeks/week-4.qmd)      |
:::